apiVersion: apps/v1
kind: Deployment
metadata:
  name: Game-deployment
  namespace: train-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-Game
  template:
    metadata:
      labels:
        app: my-Game
    spec:
      containers:
        - name:Game-container
          image: <IMAGE>
          ports:
            - containerPort: 8080
